---
- name: dftd
  hosts: all
  become: true
  become_method: sudo
  remote_user: dftd
  vars_files:
    - vars/default.yml

  tasks:
   - import_tasks: tasks/ufw.yml
   - import_tasks: tasks/users.yml
   - import_tasks: tasks/golang.yml
   - import_tasks: tasks/kubectl.yml


