apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
    type: front-end
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: nginx-2
      labels:
        app: myapp
    spec:
      containers:
      - name: nginx-container
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
  replicas: 3

# How to run the above?
# kubectl create -f deployment_k8s.yml
# kubectl get deployments
# kubectl get replicaset
# you should be able to see the changes now...
# kubectl get all
